import{Engine}from"./engine.js";
import{Renderer,short}from"./renderer.js";
import{RULES}from"./config.js";
export const BUILDINGS={fort:{id:1,name:"요새",cost:1800,description:"이 타일의 방어 비용 3배"},barracks:{id:2,name:"병영",cost:2600,description:"틱마다 병력 생산"},radar:{id:3,name:"레이더",cost:2200,description:"주변 28칸 시야·정보점 생산"},hospital:{id:4,name:"야전병원",cost:3200,description:"병력 보충 속도 증가"},shipyard:{id:6,name:"해군기지",cost:3800,description:"상륙함 이동속도 증가 · 해안 전용"}};
const coastal=(engine,tile)=>{let result=false;engine.eachNeighbor(tile,next=>{if(engine.owner[next]===-2)result=true});return result};
export function installBuildings(canvas,engine,renderer,notify=()=>{}){
  engine.buildings??=new Uint8Array(engine.owner.length);for(const nation of engine.nations)nation.buildingTiles??=new Set;
  Engine.prototype.constructBuilding=function(playerId,tile,type){const spec=BUILDINGS[type],nation=this.nations[playerId];if(!spec||this.owner[tile]!==playerId)return{ok:false,message:"내 영토에만 건설할 수 있습니다."};if(type==="shipyard"&&!coastal(this,tile))return{ok:false,message:"해군기지는 해안 타일에만 건설할 수 있습니다."};if(this.buildings[tile])return{ok:false,message:"이미 건물이 있습니다."};if((nation.buildingTiles?.size||0)>=40)return{ok:false,message:"국가 건물 한도에 도달했습니다."};if(nation.troops<spec.cost)return{ok:false,message:`병력이 부족합니다. ${short(spec.cost)} 필요`};nation.troops-=spec.cost;this.buildings[tile]=spec.id;nation.buildingTiles??=new Set;nation.buildingTiles.add(tile);this.changedTiles?.add(tile);return{ok:true,message:`${spec.name} 건설 완료`}};
  const oldTransfer=Engine.prototype.transfer;Engine.prototype.transfer=function(tile,to){const from=this.owner[tile],building=this.buildings?.[tile]||0;if(building&&from>=0){this.nations[from].buildingTiles?.delete(tile);this.buildings[tile]=0}oldTransfer.call(this,tile,to)};
  const oldStep=Engine.prototype.step;Engine.prototype.step=function(){oldStep.call(this);for(const nation of this.nations){if(!nation.alive)continue;let barracks=0,hospitals=0;for(const tile of(nation.buildingTiles||[])){if(this.buildings[tile]===2)barracks++;else if(this.buildings[tile]===4)hospitals++}if(barracks||hospitals){const cap=(RULES.popBase+nation.tiles.size*RULES.popPerTile)*1.15;if(nation.troops<cap)nation.troops=Math.min(cap,nation.troops+barracks*3.5+hospitals*1.8)}}if(this.tick%160===0)for(const nation of this.nations){if(!nation.ai||!nation.alive||(nation.buildingTiles?.size||0)>=12||nation.troops<9000||this.random()>.55)continue;const border=[...(nation.borderTiles||[])],roll=this.random(),type=border.length>90&&roll<.3?"fort":roll<.55?"barracks":roll<.75?"radar":roll<.9?"hospital":"shipyard";let tile=type==="barracks"||type==="hospital"?nation.spawn:border[this.random()*border.length|0];if(type==="shipyard"){tile=-1;for(const candidate of nation.tiles)if(!this.buildings[candidate]&&coastal(this,candidate)){tile=candidate;break}}if(tile<0||this.owner[tile]!==nation.id||this.buildings[tile]){tile=-1;for(let tries=0;tries<80;tries++){const candidate=border[this.random()*border.length|0];if(candidate>=0&&this.owner[candidate]===nation.id&&!this.buildings[candidate]&&(type!=="shipyard"||coastal(this,candidate))){tile=candidate;break}}}if(tile>=0)this.constructBuilding(nation.id,tile,type)}};
  const oldVision=Renderer.prototype.vision;Renderer.prototype.vision=function(){oldVision.call(this);const e=this.e,w=e.map.width,h=e.map.height,range=28,dirty=new Set(this.visionDirty);for(const tile of(e.nations[0].buildingTiles||[])){if(e.buildings[tile]!==3)continue;const cx=tile%w,cy=tile/w|0;for(let y=Math.max(0,cy-range);y<=Math.min(h-1,cy+range);y++)for(let x=Math.max(0,cx-range);x<=Math.min(w-1,cx+range);x++)if((x-cx)**2+(y-cy)**2<=range*range){const i=y*w+x;if(e.owner[i]!==0){this.visible[i]=Math.max(1,this.visible[i]);this.haloTiles.push(i)}this.explored[i]=1;dirty.add(i)}}this.visibleTiles=this.haloTiles;this.visionDirty=[...dirty]};
  const oldDraw=Renderer.prototype.draw;Renderer.prototype.draw=function(){oldDraw.call(this);const c=this.ctx,colors=["#000","#ffbd52","#c8ff3d","#58b8ff","#ff7898","#c38aff","#47d9d0"];for(const nation of this.e.nations)for(const tile of(nation.buildingTiles||[])){if(!this.visible[tile])continue;const type=this.e.buildings[tile],[x,y]=this.e.xy(tile),p=this.point(x+.5,y+.5),size=Math.max(2,Math.min(7,p.s*2.2));c.fillStyle=colors[type]||"#fff";c.fillRect(p.x-size/2,p.y-size/2,size,size);c.strokeStyle="#07111a";c.lineWidth=1;c.strokeRect(p.x-size/2,p.y-size/2,size,size)}};
  if(typeof document==="undefined")return;
  const panel=document.createElement("aside");panel.className="build-menu hidden";panel.innerHTML=`<button class="close">×</button><h3>건물 건설</h3><p></p><div>${Object.entries(BUILDINGS).map(([key,b])=>`<button data-build="${key}"><b>${b.name}</b><span>${short(b.cost)}</span><small>${b.description}</small></button>`).join("")}</div>`;document.body.append(panel);
  const style=document.createElement("style");style.textContent=`.build-menu{position:fixed;z-index:85;width:290px;max-height:calc(100vh - 28px);overflow:auto;padding:14px;background:#07111af2;border:1px solid #ffffff2c;color:#eef3f5}.build-menu.hidden{display:none}.build-menu h3{margin:0 0 4px}.build-menu>p{margin:0 0 10px;color:#84919a;font-size:9px}.build-menu>div{display:grid;gap:6px}.build-menu [data-build]{display:grid;grid-template-columns:1fr auto;text-align:left;padding:9px;border:1px solid #ffffff1c;background:#101b24;color:#e9eef1}.build-menu [data-build] span{color:#c8ff3d}.build-menu [data-build] small{grid-column:1/-1;color:#7f8c95;margin-top:3px}.build-menu .close{position:absolute;right:7px;top:7px;background:none;border:0;color:#fff}`;document.head.append(style);
  let selected=-1;canvas.addEventListener("contextmenu",event=>{const box=canvas.getBoundingClientRect(),tile=renderer.tile(event.clientX-box.left,event.clientY-box.top);if(tile<0||engine.owner[tile]!==0||!renderer.visible[tile])return;event.preventDefault();selected=tile;panel.style.left=Math.min(innerWidth-290,event.clientX+8)+"px";panel.style.top=Math.min(innerHeight-260,event.clientY+8)+"px";panel.querySelector("p").textContent=`좌표 ${tile%engine.map.width}, ${tile/engine.map.width|0}`;panel.classList.remove("hidden")});
  panel.querySelector(".close").onclick=()=>panel.classList.add("hidden");panel.querySelectorAll("[data-build]").forEach(button=>button.onclick=()=>{const result=engine.constructBuilding(0,selected,button.dataset.build);notify(result.message);if(result.ok)panel.classList.add("hidden")});
}
