import{RULES}from"./config.js";import{makeMap,rng}from"./map.js";
export class Engine{constructor(opts={}){this.map=opts.map??makeMap(opts.seed??77331,opts.mapType);this.random=rng(this.map.seed);this.owner=new Int16Array(this.map.land.length).fill(-2);for(let i=0;i<this.owner.length;i++)if(this.map.land[i])this.owner[i]=-1;this.nations=[];this.attacks=[];this.commands=[];this.surrenders=[];this.tick=0;this.running=false;this.winner=null;const count=(opts.aiCount||8)+1;this.isolationCheckedAt=new Int32Array(count).fill(-1);for(let id=0;id<count;id++)this.nations.push({id,name:id?`Nation ${id}`:opts.name||"플레이어",color:RULES.colors[id%RULES.colors.length],troops:RULES.initialTroops,tiles:new Set,borderTiles:new Set,spawn:-1,alive:true,ai:id>0})}
 xy(i){return[i%this.map.width,i/this.map.width|0]}index(x,y){return y*this.map.width+x}eachNeighbor(i,fn){const w=this.map.width,x=i%w;if(x)fn(i-1);if(x<w-1)fn(i+1);if(i>=w)fn(i-w);if(i<this.owner.length-w)fn(i+w)}
 refreshBorder(i){const id=this.owner[i];if(id<0)return;let edge=false;this.eachNeighbor(i,n=>{if(this.owner[n]!==id&&this.owner[n]!==-2)edge=true});const border=this.nations[id].borderTiles??=new Set;if(edge)border.add(i);else border.delete(i)}
 transfer(i,to){const from=this.owner[i];if(from===to)return;const affected=[i];this.eachNeighbor(i,n=>affected.push(n));if(from>=0){this.nations[from].tiles.delete(i);this.nations[from].borderTiles?.delete(i)}this.owner[i]=to;if(to>=0)this.nations[to].tiles.add(i);for(const tile of affected)this.refreshBorder(tile)}
 validSpawn(i){if(this.owner[i]!==-1||(this.map.riverMask?.[i]||0)>0)return false;const[x,y]=this.xy(i),r=9;for(let yy=Math.max(0,y-r);yy<=Math.min(this.map.height-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(this.map.width-1,x+r);xx++)if(this.owner[this.index(xx,yy)]===-2)return false;return this.nations.every(n=>n.spawn<0||(()=>{const[a,b]=this.xy(n.spawn);return Math.hypot(a-x,b-y)>=RULES.spawnDistance})())}
 spawn(id,i){if(!this.validSpawn(i))return false;const[x,y]=this.xy(i),r=RULES.spawnRadius;this.nations[id].spawn=i;for(let yy=y-r;yy<=y+r;yy++)for(let xx=x-r;xx<=x+r;xx++)if(xx>=0&&yy>=0&&xx<this.map.width&&yy<this.map.height&&Math.hypot(xx-x,yy-y)<=r+.4){const t=this.index(xx,yy);if(this.owner[t]===-1)this.transfer(t,id)}return true}
 autoSpawn(id){for(let n=0;n<5000;n++){const i=this.random()*this.owner.length|0;if(this.spawn(id,i))return true}return false}start(){for(const n of this.nations)if(n.spawn<0)this.autoSpawn(n.id);this.running=true}
 issue(c){if(c.type!=="attack")return false;const targetOwner=Number(c.targetOwner);if(!Number.isInteger(targetOwner)||targetOwner<-1||targetOwner>=this.nations.length)return false;this.commands.push({type:"attack",playerId:c.playerId,target:c.target,targetOwner,percent:c.percent});return true}sharedBorder(a,b){const out=[];for(const i of(this.nations[a].borderTiles||this.nations[a].tiles)){let hit=false;this.eachNeighbor(i,n=>{if(this.owner[n]===b)hit=true});if(hit)out.push(i)}return out}
 begin(c){const nation=this.nations[c.playerId],target=c.targetOwner;if(!nation?.alive||target===nation.id||target===-2)return;const border=this.sharedBorder(nation.id,target);if(!border.length)return;const amount=Math.floor(nation.troops*Math.max(.05,Math.min(.9,c.percent/100)));if(amount<30)return;const existing=this.attacks.find(a=>a.alive!==false&&a.attacker===nation.id&&a.defender===target);nation.troops-=amount;if(existing){existing.power+=amount;existing.committed+=amount;existing.paused=false;return}const front=new Set(border),focus=target>=0?this.nations[target].spawn:border[0];this.attacks.push({id:`${this.tick}-${nation.id}-${this.attacks.length}`,attacker:nation.id,defender:target,target:focus,committed:amount,power:amount,front,captured:0,alive:true})}
 advance(a){if(!this.nations[a.attacker].alive||a.power<3)return false;const candidates=new Map;for(const f of a.front)this.eachNeighbor(f,n=>{if(this.owner[n]!==a.defender)return;let friends=0;this.eachNeighbor(n,m=>{if(this.owner[m]===a.attacker)friends++});candidates.set(n,Math.max(candidates.get(n)||0,friends))});if(!candidates.size)return false;const attacker=this.nations[a.attacker],defender=a.defender>=0?this.nations[a.defender]:null,defense=defender?Math.max(1,defender.troops):a.power,ratio=a.power/defense*(attacker.attackModifier||1)/(defender?.defenseModifier||1),budget=a.defender<0?Math.min(RULES.captureMax,24+Math.floor(Math.sqrt(a.power)/8)):Math.max(2,Math.min(RULES.captureMax,Math.round(RULES.captureBase*Math.sqrt(Math.max(.05,ratio))))),[tx,ty]=this.xy(a.target),frontier=[...candidates].map(([tile,f])=>{const[x,y]=this.xy(tile);return{tile,f,angle:Math.atan2(y-ty,x-tx),distance:(x-tx)**2+(y-ty)**2,jitter:this.random()}}).sort((p,q)=>p.angle-q.angle||p.distance-q.distance||p.jitter-q.jitter),limit=Math.min(budget,frontier.length),offset=this.random(),ordered=limit===frontier.length?frontier:Array.from({length:limit},(_,k)=>frontier[Math.min(frontier.length-1,Math.floor((k+offset)*frontier.length/limit))]),next=new Set;let changed=0;for(let k=0;k<ordered.length;k++){const tile=ordered[k].tile,cost=defender?Math.max(4,Math.ceil(defender.troops/Math.max(1,defender.tiles.size)*.35)):RULES.neutralCost;if(a.power<cost)break;a.power-=cost;if(defender)defender.troops=Math.max(0,defender.troops-cost*(ratio>1?.48:.3));this.transfer(tile,a.attacker);next.add(tile);changed++;a.captured++}for(const f of a.front){let touch=false;this.eachNeighbor(f,n=>{if(this.owner[n]===a.defender)touch=true});if(touch)next.add(f)}a.front=next;const isolationInterval=this.nations.length>40?30:RULES.surrenderCheckTicks;if(defender&&changed&&(this.tick%isolationInterval===0||this.owner[defender.spawn]!==defender.id))this.checkIsolation(a);return changed>0&&next.size>0&&a.power>=3}
 checkIsolation(a){const d=this.nations[a.defender];if(!d?.alive||!d.tiles.size||this.isolationCheckedAt[a.defender]===this.tick||this.surrenders.some(s=>s.defender===a.defender))return;this.isolationCheckedAt[a.defender]=this.tick;if(this.owner[d.spawn]!==d.id){this.queueSurrender(a,[...d.tiles],"수도 함락");return}const reached=new Set([d.spawn]),q=[d.spawn];for(let h=0;h<q.length;h++)this.eachNeighbor(q[h],n=>{if(this.owner[n]===d.id&&!reached.has(n)){reached.add(n);q.push(n)}});if(reached.size===d.tiles.size)return;const isolated=[...d.tiles].filter(i=>!reached.has(i));if(isolated.length<=Math.max(1800,d.tiles.size*.38))this.queueSurrender(a,isolated,"고립 영토 항복")}
 queueSurrender(a,tiles,reason){if(this.surrenders.some(s=>s.defender===a.defender))return;const pending=tiles.filter(i=>this.owner[i]===a.defender);if(!pending.length)return;this.surrenders.push({attacker:a.attacker,defender:a.defender,tiles:pending,reason});a.front=new Set([...a.front,...pending.slice(0,20)])}
 processSurrenders(){this.surrenders=this.surrenders.filter(s=>{for(let n=0;n<RULES.surrenderBatch&&s.tiles.length;n++){const pick=this.random()*s.tiles.length|0,tile=s.tiles[pick];s.tiles[pick]=s.tiles.at(-1);s.tiles.pop();if(this.owner[tile]===s.defender)this.transfer(tile,s.attacker)}return s.tiles.length>0})}
  step(){if(!this.running||this.winner!==null)return;this.tick++;for(const c of this.commands)this.begin(c);this.commands.length=0;this.attacks=this.attacks.filter(a=>this.advance(a));this.processSurrenders();for(const n of this.nations){if(!n.alive)continue;if(n.spawn>=0&&!n.tiles.size){n.alive=false;continue}const max=RULES.popBase+n.tiles.size*RULES.popPerTile;if(n.troops<max){const g=(RULES.baseGrowth+n.tiles.size*RULES.tileGrowth)*(1-n.troops/max*.55)*(n.growthModifier||1);n.troops=Math.min(max,n.troops+Math.max(1,g))}}if(this.tick%20===0){const alive=this.nations.filter(n=>n.alive&&n.spawn>=0);if(alive.length===1){this.winner=alive[0].id;this.running=false}}}
}
